# Generated by Django 5.0.7 on 2024-07-24 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile no')),
                ('partner_category', models.CharField(choices=[('1', 'person'), ('2', 'organization'), ('3', 'group')], max_length=1, verbose_name='Partner')),
                ('organisation', models.IntegerField()),
                ('gst_number', models.CharField(max_length=64, verbose_name='GST Number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('gst_number', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Active'), ('2', 'Expired')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_organisation', models.IntegerField()),
                ('po_number', models.CharField(max_length=32, verbose_name='PO Number')),
                ('business_partner', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'registered'), ('2', 'approved'), ('3', 'confirmed'), ('4', 'cancelled'), ('5', 'delivered')], max_length=1, verbose_name='Status')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('total_value', models.IntegerField(verbose_name='Total Value')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_code', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('domain', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Active'), ('2', 'Expired')], max_length=1, null=True)),
            ],
        ),
    ]
